spring.application.name=factura

# spring.mail.host=sandbox.smtp.mailtrap.io
# spring.mail.port=2525
# spring.mail.username=d4b835d52a3097
# spring.mail.password=7fc22ebfbb6f76
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true

# Configuración Outlook
# spring.mail.host=smtp.office365.com
# spring.mail.port=587
# spring.mail.username=danielaguevara09@outlook.com
# spring.mail.password=25.11.Dani.09.06
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true

# Configuración de Outlook Personal
# spring.mail.host=smtp.office365.com
# spring.mail.port=587
# spring.mail.username=danielaguevara09@outlook.com
# spring.mail.password=rkwndoiytmvytgzu
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true

# Configuración de Gmail Personal
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lauradanielaguevara09@gmail.com
spring.mail.password=ezutimcezzxwwrip
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
