spring.application.name=factura

# Configuración de Gmail SMTP (Puerto 465 SSL para Servidores en la Nube / Render)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=lauradanielaguevara09@gmail.com
spring.mail.password=ezutimcezzxwwrip
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
